In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('operations_WW2.csv')
df

<ipython-input-1-244870b6610f>:5: DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('operations_WW2.csv')

,Mission ID,Mission Date,Theater of Operations,Country,Air Force,Unit ID,Aircraft Series,Callsign,Mission Type,Takeoff Base,...,Incendiary Devices Weight (Tons),Fragmentation Devices,Fragmentation Devices Type,Fragmentation Devices Weight (Pounds),Fragmentation Devices Weight (Tons),Total Weight (Pounds),Total Weight (Tons),Time Over Target,Bomb Damage Assessment,Source ID
0,1,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN
1,2,8/15/1943,PTO,USA,5 AF,400 BS,B24,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,9366.0
2,3,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN
3,4,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,7.5,NaN,NaN,NaN
4,5,8/15/1943,PTO,USA,5 AF,321 BS,B24,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,22585.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178276,178738,2/16/1945,CBI,USA,10 AF,89 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,35815.0
178277,178739,2/16/1945,CBI,USA,10 AF,90 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,35020.0
178278,178740,2/16/1945,CBI,USA,10 AF,90 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,35022.0
178279,178741,2/16/1945,PTO,NEW ZEALAND,RNZAF,NO. 22 SQUADRON RNZAF,F4U,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8000.0,4.0,NaN,NaN,NaN
178280,178742,2/16/1945,CBI,USA,10 AF,59 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,33784.0

In [2]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178281 entries, 0 to 178280
Data columns (total 46 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Mission ID                             178281 non-null  int64
 1   Mission Date                           178281 non-null  object
 2   Theater of Operations                  175123 non-null  object
 3   Country                                126494 non-null  object
 4   Air Force                              126444 non-null  object
 5   Unit ID                                50913 non-null   object
 6   Aircraft Series                        178165 non-null  object
 7   Callsign                               21 non-null      object
 8   Mission Type                           47186 non-null   object
 9   Takeoff Base                           3383 non-null    object
 10  Takeoff Location                       3338 non-null    object
 11  Takeoff Latitude                       2981 non-null    object
 12  Takeoff Longitude                      2980 non-null    float64
 13  Target ID                              127406 non-null  object
 14  Target Country                         177682 non-null  object
 15  Target City                            176018 non-null  object
 16  Target Type                            146370 non-null  object
 17  Target Industry                        126479 non-null  object
 18  Target Priority                        134720 non-null  object
 19  Target Latitude                        169565 non-null  float64
 20  Target Longitude                       169543 non-null  float64
 21  Altitude (Hundreds of Feet)            120826 non-null  float64
 22  Airborne Aircraft                      82242 non-null   float64
 23  Attacking Aircraft                     125108 non-null  float64
 24  Bombing Aircraft                       81612 non-null   float64
 25  Aircraft Returned                      133 non-null     float64
 26  Aircraft Failed                        247 non-null     float64
 27  Aircraft Damaged                       38 non-null      float64
 28  Aircraft Lost                          158 non-null     float64
 29  High Explosives                        34737 non-null   float64
 30  High Explosives Type                   41945 non-null   object
 31  High Explosives Weight (Pounds)        2021 non-null    object
 32  High Explosives Weight (Tons)          146201 non-null  float64
 33  Incendiary Devices                     3283 non-null    float64
 34  Incendiary Devices Type                5519 non-null    object
 35  Incendiary Devices Weight (Pounds)     356 non-null     float64
 36  Incendiary Devices Weight (Tons)       25732 non-null   float64
 37  Fragmentation Devices                  5768 non-null    float64
 38  Fragmentation Devices Type             5765 non-null    object
 39  Fragmentation Devices Weight (Pounds)  194 non-null     float64
 40  Fragmentation Devices Weight (Tons)    16902 non-null   float64
 41  Total Weight (Pounds)                  2119 non-null    float64
 42  Total Weight (Tons)                    166508 non-null  float64
 43  Time Over Target                       689 non-null     object
 44  Bomb Damage Assessment                 104 non-null     object
 45  Source ID                              174236 non-null  float64
dtypes: float64(22), int64(1), object(23)
memory usage: 46.9+ MB

,Mission ID,Takeoff Longitude,Target Latitude,Target Longitude,Altitude (Hundreds of Feet),Airborne Aircraft,Attacking Aircraft,Bombing Aircraft,Aircraft Returned,Aircraft Failed,...,High Explosives Weight (Tons),Incendiary Devices,Incendiary Devices Weight (Pounds),Incendiary Devices Weight (Tons),Fragmentation Devices,Fragmentation Devices Weight (Pounds),Fragmentation Devices Weight (Tons),Total Weight (Pounds),Total Weight (Tons),Source ID
count,178281.000000,2980.000000,169565.000000,169543.000000,120826.000000,82242.000000,125108.000000,81612.000000,133.000000,247.000000,...,146201.000000,3283.000000,356.000000,25732.000000,5768.000000,194.000000,16902.000000,2.119000e+03,166508.000000,174236.000000
mean,89414.547041,220.618627,38.067793,43.340213,139.026812,12.329771,10.218899,12.347486,2.157895,4.275304,...,23.911995,132.001965,19962.732022,21.527213,102.684560,2065.630928,12.017136,1.237718e+04,25.760326,152670.902322
std,51649.744549,454.046956,18.711405,59.681160,186.818278,12.514833,11.246399,12.573549,1.369816,5.924758,...,90.092020,498.596761,45331.714255,66.692639,158.941650,2424.138566,27.221410,2.064155e+05,90.643876,105544.795936
min,1.000000,-177.328611,-37.416667,-179.451285,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000
25%,44571.000000,14.400000,26.250000,7.620000,70.000000,2.000000,2.000000,2.000000,1.000000,1.000000,...,2.000000,7.000000,218.750000,1.000000,10.000000,598.400000,1.000000,2.100000e+03,2.000000,53476.500000
50%,89540.000000,29.851389,47.500000,11.330000,122.000000,11.000000,7.000000,11.000000,2.000000,2.000000,...,9.000000,14.000000,2640.000000,6.000000,38.461538,1500.000000,3.000000,5.200000e+03,9.290000,167604.500000
75%,134171.000000,96.133222,50.930000,97.400000,223.000000,17.000000,12.000000,18.000000,3.000000,4.000000,...,30.000000,32.000000,12500.000000,18.000000,133.333333,2400.000000,12.000000,1.080000e+04,31.000000,211284.250000
max,178742.000000,1355.000000,1108.000000,1000.650000,40000.000000,332.000000,332.000000,332.000000,7.000000,48.000000,...,20000.000000,4875.000000,420000.000000,999.000000,3000.000000,20640.000000,900.000000,9.500000e+06,20000.000000,699625.000000

In [3]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Mission ID,178281.0,89414.547041,51649.744549,1.000000,44571.00,89540.000000,134171.000000,178742.00
Takeoff Longitude,2980.0,220.618627,454.046956,-177.328611,14.40,29.851389,96.133222,1355.00
Target Latitude,169565.0,38.067793,18.711405,-37.416667,26.25,47.500000,50.930000,1108.00
Target Longitude,169543.0,43.340213,59.681160,-179.451285,7.62,11.330000,97.400000,1000.65
Altitude (Hundreds of Feet),120826.0,139.026812,186.818278,0.000000,70.00,122.000000,223.000000,40000.00
Airborne Aircraft,82242.0,12.329771,12.514833,0.000000,2.00,11.000000,17.000000,332.00
Attacking Aircraft,125108.0,10.218899,11.246399,0.000000,2.00,7.000000,12.000000,332.00
Bombing Aircraft,81612.0,12.347486,12.573549,0.000000,2.00,11.000000,18.000000,332.00
Aircraft Returned,133.0,2.157895,1.369816,1.000000,1.00,2.000000,3.000000,7.00
Aircraft Failed,247.0,4.275304,5.924758,1.000000,1.00,2.000000,4.000000,48.00
Aircraft Damaged,38.0,2.052632,1.675699,0.000000,1.00,1.500000,2.750000,9.00
Aircraft Lost,158.0,2.279253,6.414377,0.000000,1.00,1.000000,2.000000,80.00
High Explosives,34737.0,33.331215,105.356530,0.000000,8.00,16.000000,36.000000,10000.00
High Explosives Weight (Tons),146201.0,23.911995,90.092020,0.000000,2.00,9.000000,30.000000,20000.00
Incendiary Devices,3283.0,132.001965,498.596761,0.000000,7.00,14.000000,32.000000,4875.00
Incendiary Devices Weight (Pounds),356.0,19962.732022,45331.714255,0.000000,218.75,2640.000000,12500.000000,420000.00
Incendiary Devices Weight (Tons),25732.0,21.527213,66.692639,0.000000,1.00,6.000000,18.000000,999.00
Fragmentation Devices,5768.0,102.684560,158.941650,0.000000,10.00,38.461538,133.333333,3000.00
Fragmentation Devices Weight (Pounds),194.0,2065.630928,2424.138566,0.000000,598.40,1500.000000,2400.000000,20640.00
Fragmentation Devices Weight (Tons),16902.0,12.017136,27.221410,0.000000,1.00,3.000000,12.000000,900.00
Total Weight (Pounds),2119.0,12377.178386,206415.492804,0.000000,2100.00,5200.000000,10800.000000,9500000.00
Total Weight (Tons),166508.0,25.760326,90.643876,0.000000,2.00,9.290000,31.000000,20000.00
Source ID,174236.0,152670.902322,105544.795936,1.000000,53476.50,167604.500000,211284.250000,699625.00

In [4]:
df.isnull().sum()

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                     136336
High Explosives Weight (Pounds)          176260
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                  172762
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type               172516
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)      161379
Total Weight (Pounds)                    176162
Total Weight (Tons)                       11773
Time Over Target                         177592
Bomb Damage Assessment                   178177
Source ID                                  4045
dtype: int64

In [5]:
df_filled = df.fillna(df.mean(numeric_only=True))
print("\nMissing values after:")
print(df_filled.isnull().sum())

Missing values after:
Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                             0
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                               0
Target Longitude                              0
Altitude (Hundreds of Feet)                   0
Airborne Aircraft                             0
Attacking Aircraft                            0
Bombing Aircraft                              0
Aircraft Returned                             0
Aircraft Failed                               0
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                     136336
High Explosives Weight (Pounds)          176260
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                  172762
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type               172516
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                         177592
Bomb Damage Assessment                   178177
Source ID                                     0
dtype: int64

In [17]:
df['Source ID'] = df['Source ID'].fillna('NA')
df['Source ID'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)      161379
Total Weight (Pounds)                    176162
Total Weight (Tons)                       11773
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [18]:
df['Time Over Target'] = df['Time Over Target'].fillna('NA')
df['Time Over Target'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)      161379
Total Weight (Pounds)                    176162
Total Weight (Tons)                       11773
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [20]:
df['Bomb Damage Assessment'] = df['Bomb Damage Assessment'].fillna('NA')
df['Bomb Damage Assessment'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)      161379
Total Weight (Pounds)                    176162
Total Weight (Tons)                       11773
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [22]:
df['Total Weight (Tons)'] = df['Total Weight (Tons)'].fillna('NA')
df['Total Weight (Tons)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)      161379
Total Weight (Pounds)                    176162
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [23]:
df['Total Weight (Pounds)'] = df['Total Weight (Pounds)'].fillna('NA')
df['Total Weight (Pounds)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)      161379
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [24]:
df['Fragmentation Devices Weight (Tons)'] = df['Fragmentation Devices Weight (Tons)'].fillna('NA')
df['Fragmentation Devices Weight (Tons)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [25]:
df['Fragmentation Devices Weight (Pounds)'] = df['Fragmentation Devices Weight (Pounds)'].fillna('NA')
df['Fragmentation Devices Weight (Pounds)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [28]:
df['Fragmentation Devices Type'] = df['Fragmentation Devices Type'].fillna('NA')
df['Fragmentation Devices Type'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [29]:
df['Fragmentation Devices'] = df['Fragmentation Devices'].fillna('NA')
df['Fragmentation Devices'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [30]:
df['Incendiary Devices Weight (Tons)'] = df['Incendiary Devices Weight (Tons)'].fillna('NA')
df['Incendiary Devices Weight (Tons)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [31]:
df['Incendiary Devices Weight (Pounds)'] = df['Incendiary Devices Weight (Pounds)'].fillna('NA')
df['Incendiary Devices Weight (Pounds)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [27]:
df['Incendiary Devices Type'] = df['Incendiary Devices Type'].fillna('NA')
df['Incendiary Devices Type'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [32]:
df['Fragmentation Devices'] = df['Fragmentation Devices'].fillna('NA')
df['Fragmentation Devices'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [33]:
df['Incendiary Devices'] = df['Incendiary Devices'].fillna('NA')
df['Incendiary Devices'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)             32080
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [34]:
df['High Explosives Weight (Tons)'] = df['High Explosives Weight (Tons)'].fillna('NA')
df['High Explosives Weight (Tons)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [35]:
df['High Explosives Weight (Pounds)'] = df['High Explosives Weight (Pounds)'].fillna('NA')
df['High Explosives Weight (Pounds)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [36]:
df['High Explosives Type'] = df['High Explosives Type'].fillna('NA')
df['High Explosives Type'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [37]:
df['High Explosives'] = df['High Explosives'].fillna('NA')
df['High Explosives'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [38]:
df['Aircraft Lost'] = df['Aircraft Lost'].fillna('NA')
df['Aircraft Lost'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [39]:
df['Aircraft Damaged'] = df['Aircraft Damaged'].fillna('NA')
df['Aircraft Damaged'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [41]:
df['Aircraft Failed'] = df['Aircraft Failed'].fillna('NA')
df['Aircraft Failed'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                               0
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [42]:
df['Aircraft Returned'] = df['Aircraft Returned'].fillna('NA')
df['Aircraft Returned'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                             0
Aircraft Failed                               0
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [43]:
df['Bombing Aircraft'] = df['Bombing Aircraft'].fillna('NA')
df['Bombing Aircraft'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                              0
Aircraft Returned                             0
Aircraft Failed                               0
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [44]:
df['Attacking Aircraft'] = df['Attacking Aircraft'].fillna('NA')
df['Attacking Aircraft'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                            0
Bombing Aircraft                              0
Aircraft Returned                             0
Aircraft Failed                               0
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [45]:
df['Airborne Aircraft'] = df['Airborne Aircraft'].fillna('NA')
df['Airborne Aircraft'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                             0
Attacking Aircraft                            0
Bombing Aircraft                              0
Aircraft Returned                             0
Aircraft Failed                               0
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64

In [46]:
df['Altitude (Hundreds of Feet)'] = df['Altitude (Hundreds of Feet)'].fillna('NA')
df['Altitude (Hundreds of Feet)'].isnull().sum()
print(df.isnull().sum())

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)                   0
Airborne Aircraft                             0
Attacking Aircraft                            0
Bombing Aircraft                              0
Aircraft Returned                             0
Aircraft Failed                               0
Aircraft Damaged                              0
Aircraft Lost                                 0
High Explosives                               0
High Explosives Type                          0
High Explosives Weight (Pounds)               0
High Explosives Weight (Tons)                 0
Incendiary Devices                            0
Incendiary Devices Type                       0
Incendiary Devices Weight (Pounds)            0
Incendiary Devices Weight (Tons)              0
Fragmentation Devices                         0
Fragmentation Devices Type                    0
Fragmentation Devices Weight (Pounds)         0
Fragmentation Devices Weight (Tons)           0
Total Weight (Pounds)                         0
Total Weight (Tons)                           0
Time Over Target                              0
Bomb Damage Assessment                        0
Source ID                                     0
dtype: int64