In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Bookings.csv')
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,#NAME?,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,NaN,384,NaN,0,NaN,NaN,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 9:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,...,NaN,No,NaN,111,Cash,41,3.6,3.8,#NAME?,NaN
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,...,NaN,No,NaN,1097,UPI,17,4.3,3.3,#NAME?,NaN
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,...,NaN,No,NaN,2201,Cash,37,3.6,3.2,#NAME?,NaN
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,...,NaN,No,NaN,267,UPI,47,3.4,3.1,#NAME?,NaN
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,...,NaN,No,NaN,462,UPI,3,4.8,4.4,#NAME?,NaN

In [2]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  object
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
 20  Unnamed: 20                 0 non-null       float64
dtypes: float64(5), int64(2), object(14)
memory usage: 16.5+ MB

,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating,Unnamed: 20
count,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000,0.0
mean,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313,NaN
std,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957,NaN
min,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000,NaN
25%,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000,NaN
50%,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000,NaN
75%,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000,NaN
max,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000,NaN

In [3]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
V_TAT,63967.0,170.876952,80.803640,35.0,98.0,168.0,238.0,308.0
C_TAT,63967.0,84.873372,36.005100,25.0,55.0,85.0,115.0,145.0
Booking_Value,103024.0,548.751883,536.541221,100.0,242.0,386.0,621.0,2999.0
Ride_Distance,103024.0,14.189927,15.776270,0.0,0.0,8.0,26.0,49.0
Driver_Ratings,63967.0,3.997457,0.576834,3.0,3.5,4.0,4.5,5.0
Customer_Rating,63967.0,3.998313,0.578957,3.0,3.5,4.0,4.5,5.0
Unnamed: 20,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()
print("Categorical Columns:", cat_cols)
print("Numerical Columns:", num_cols)

for col in cat_cols:
   print(f"\nValues for counts '{col}':")
   print(df[col].value_counts())

Categorical Columns: ['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver', 'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Payment_Method', 'Vehicle Images']
Numerical Columns: ['V_TAT', 'C_TAT', 'Booking_Value', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating', 'Unnamed: 20']

Values for counts 'Date':
Date
2024-07-01 20:09:00    10
2024-07-13 18:53:00    10
2024-07-05 11:58:00    10
2024-07-25 5:20:00     10
2024-07-10 14:03:00    10
                       ..
2024-07-31 12:41:00     1
2024-07-31 2:44:00      1
2024-07-31 12:43:00     1
2024-07-31 9:09:00      1
2024-07-31 5:36:00      1
Name: count, Length: 40214, dtype: int64

Values for counts 'Time':
Time
00:53:00    101
22:12:00     97
01:13:00     96
09:29:00     95
14:34:00     95
           ...
18:19:00     50
23:28:00     49
00:02:00     48
04:39:00     48
02:22:00     42
Name: count, Length: 1440, dtype: int64

Values for counts 'Booking_ID':
Booking_ID
CNR3204013257    1
CNR5979995999    1
CNR3766293727    1
CNR1573041532    1
CNR2619112624    1
                ..
CNR1797421769    1
CNR2395710036    1
CNR2982357879    1
CNR2940424040    1
CNR7153255142    1
Name: count, Length: 103024, dtype: int64

Values for counts 'Booking_Status':
Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

Values for counts 'Customer_ID':
Customer_ID
CID954071    5
CID782883    4
CID952434    4
CID539191    4
CID819034    4
            ..
CID447657    1
CID259449    1
CID296711    1
CID561720    1
CID611001    1
Name: count, Length: 94544, dtype: int64

Values for counts 'Vehicle_Type':
Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64

Values for counts 'Pickup_Location':
Pickup_Location
Banashankari            2201
Yeshwanthpur            2139
RT Nagar                2135
Indiranagar             2133
Sahakar Nagar           2126
Basavanagudi            2120
Ramamurthy Nagar        2116
Vijayanagar             2113
Tumkur Road             2105
Cox Town                2100
Magadi Road             2099
BTM Layout              2091
Hennur                  2090
Whitefield              2087
Mysore Road             2085
Nagarbhavi              2083
Kengeri                 2083
Langford Town           2079
Hosur Road              2074
Kammanahalli            2071
Sarjapur Road           2070
Peenya                  2069
Majestic                2067
Koramangala             2062
Hebbal                  2058
KR Puram                2058
Malleshwaram            2058
MG Road                 2048
Frazer Town             2048
Bannerghatta Road       2046
Yelahanka               2044
Electronic City         2044
HSR Layout              2042
Richmond Town           2042
JP Nagar                2039
Ulsoor                  2038
Rajarajeshwari Nagar    2037
Hulimavu                2030
Marathahalli            2027
Shivajinagar            2017
Varthur                 2013
Shantinagar             2012
Bellandur               2008
Padmanabhanagar         2004
Kadugodi                2002
Devanahalli             1999
Chickpet                1994
Jayanagar               1985
Chamarajpet             1981
Rajajinagar             1952
Name: count, dtype: int64

Values for counts 'Drop_Location':
Drop_Location
Peenya                  2159
Mysore Road             2148
MG Road                 2128
Hennur                  2120
HSR Layout              2117
Sarjapur Road           2108
Koramangala             2105
Marathahalli            2104
Vijayanagar             2103
Hebbal                  2097
BTM Layout              2096
Sahakar Nagar           2093
Bannerghatta Road       2091
RT Nagar                2089
Kadugodi                2088
JP Nagar                2088
Kengeri                 2085
Jayanagar               2073
Hosur Road              2073
Banashankari            2072
Frazer Town             2070
Shivajinagar            2068
Majestic                2067
Kammanahalli            2067
Tumkur Road             2060
Langford Town           2059
Devanahalli             2055
Malleshwaram            2054
Magadi Road             2053
Hulimavu                2051
Rajajinagar             2050
Yeshwanthpur            2048
KR Puram                2048
Basavanagudi            2041
Bellandur               2040
Padmanabhanagar         2037
Shantinagar             2036
Chamarajpet             2034
Chickpet                2033
Varthur                 2026
Ulsoor                  2023
Nagarbhavi              2017
Electronic City         2014
Rajarajeshwari Nagar    2010
Indiranagar             2009
Richmond Town           2004
Cox Town                2002
Ramamurthy Nagar        1995
Yelahanka               1993
Whitefield              1923
Name: count, dtype: int64

Values for counts 'Canceled_Rides_by_Customer':
Canceled_Rides_by_Customer
Driver is not moving towards pickup location    3175
Driver asked to cancel                          2670
Change of plans                                 2081
AC is Not working                               1568
Wrong Address                                   1005
Name: count, dtype: int64

Values for counts 'Canceled_Rides_by_Driver':
Canceled_Rides_by_Driver
Personal & Car related issue           6542
Customer related issue                 5413
Customer was coughing/sick             3654
More than permitted people in there    2825
Name: count, dtype: int64

Values for counts 'Incomplete_Rides':
Incomplete_Rides
No     60041
Yes     3926
Name: count, dtype: int64

Values for counts 'Incomplete_Rides_Reason':
Incomplete_Rides_Reason
Customer Demand      1601
Vehicle Breakdown    1591
Other Issue           734
Name: count, dtype: int64

Values for counts 'Payment_Method':
Payment_Method
Cash           35022
UPI            25881
Credit Card     2435
Debit Card       629
Name: count, dtype: int64

Values for counts 'Vehicle Images':
Vehicle Images
#NAME?    103024
Name: count, dtype: int64

In [5]:
df['Unnamed: 20'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Unnamed: 20, dtype: float64

In [6]:
df.drop(columns=['Unnamed: 20'], inplace=True)

In [7]:
df.drop(columns=['Vehicle Images'], inplace=True)

In [8]:
df.shape

(103024, 19)

In [9]:
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()
print("Categorical Columns:", cat_cols)
print("Numerical Columns:", num_cols)

for col in cat_cols:
   print(f"\nValues for counts '{col}':")
   print(df[col].value_counts())

Categorical Columns: ['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver', 'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Payment_Method']
Numerical Columns: ['V_TAT', 'C_TAT', 'Booking_Value', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating']

Values for counts 'Date':
Date
2024-07-01 20:09:00    10
2024-07-13 18:53:00    10
2024-07-05 11:58:00    10
2024-07-25 5:20:00     10
2024-07-10 14:03:00    10
                       ..
2024-07-31 12:41:00     1
2024-07-31 2:44:00      1
2024-07-31 12:43:00     1
2024-07-31 9:09:00      1
2024-07-31 5:36:00      1
Name: count, Length: 40214, dtype: int64

Values for counts 'Time':
Time
00:53:00    101
22:12:00     97
01:13:00     96
09:29:00     95
14:34:00     95
           ...
18:19:00     50
23:28:00     49
00:02:00     48
04:39:00     48
02:22:00     42
Name: count, Length: 1440, dtype: int64

Values for counts 'Booking_ID':
Booking_ID
CNR3204013257    1
CNR5979995999    1
CNR3766293727    1
CNR1573041532    1
CNR2619112624    1
                ..
CNR1797421769    1
CNR2395710036    1
CNR2982357879    1
CNR2940424040    1
CNR7153255142    1
Name: count, Length: 103024, dtype: int64

Values for counts 'Booking_Status':
Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

Values for counts 'Customer_ID':
Customer_ID
CID954071    5
CID782883    4
CID952434    4
CID539191    4
CID819034    4
            ..
CID447657    1
CID259449    1
CID296711    1
CID561720    1
CID611001    1
Name: count, Length: 94544, dtype: int64

Values for counts 'Vehicle_Type':
Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64

Values for counts 'Pickup_Location':
Pickup_Location
Banashankari            2201
Yeshwanthpur            2139
RT Nagar                2135
Indiranagar             2133
Sahakar Nagar           2126
Basavanagudi            2120
Ramamurthy Nagar        2116
Vijayanagar             2113
Tumkur Road             2105
Cox Town                2100
Magadi Road             2099
BTM Layout              2091
Hennur                  2090
Whitefield              2087
Mysore Road             2085
Nagarbhavi              2083
Kengeri                 2083
Langford Town           2079
Hosur Road              2074
Kammanahalli            2071
Sarjapur Road           2070
Peenya                  2069
Majestic                2067
Koramangala             2062
Hebbal                  2058
KR Puram                2058
Malleshwaram            2058
MG Road                 2048
Frazer Town             2048
Bannerghatta Road       2046
Yelahanka               2044
Electronic City         2044
HSR Layout              2042
Richmond Town           2042
JP Nagar                2039
Ulsoor                  2038
Rajarajeshwari Nagar    2037
Hulimavu                2030
Marathahalli            2027
Shivajinagar            2017
Varthur                 2013
Shantinagar             2012
Bellandur               2008
Padmanabhanagar         2004
Kadugodi                2002
Devanahalli             1999
Chickpet                1994
Jayanagar               1985
Chamarajpet             1981
Rajajinagar             1952
Name: count, dtype: int64

Values for counts 'Drop_Location':
Drop_Location
Peenya                  2159
Mysore Road             2148
MG Road                 2128
Hennur                  2120
HSR Layout              2117
Sarjapur Road           2108
Koramangala             2105
Marathahalli            2104
Vijayanagar             2103
Hebbal                  2097
BTM Layout              2096
Sahakar Nagar           2093
Bannerghatta Road       2091
RT Nagar                2089
Kadugodi                2088
JP Nagar                2088
Kengeri                 2085
Jayanagar               2073
Hosur Road              2073
Banashankari            2072
Frazer Town             2070
Shivajinagar            2068
Majestic                2067
Kammanahalli            2067
Tumkur Road             2060
Langford Town           2059
Devanahalli             2055
Malleshwaram            2054
Magadi Road             2053
Hulimavu                2051
Rajajinagar             2050
Yeshwanthpur            2048
KR Puram                2048
Basavanagudi            2041
Bellandur               2040
Padmanabhanagar         2037
Shantinagar             2036
Chamarajpet             2034
Chickpet                2033
Varthur                 2026
Ulsoor                  2023
Nagarbhavi              2017
Electronic City         2014
Rajarajeshwari Nagar    2010
Indiranagar             2009
Richmond Town           2004
Cox Town                2002
Ramamurthy Nagar        1995
Yelahanka               1993
Whitefield              1923
Name: count, dtype: int64

Values for counts 'Canceled_Rides_by_Customer':
Canceled_Rides_by_Customer
Driver is not moving towards pickup location    3175
Driver asked to cancel                          2670
Change of plans                                 2081
AC is Not working                               1568
Wrong Address                                   1005
Name: count, dtype: int64

Values for counts 'Canceled_Rides_by_Driver':
Canceled_Rides_by_Driver
Personal & Car related issue           6542
Customer related issue                 5413
Customer was coughing/sick             3654
More than permitted people in there    2825
Name: count, dtype: int64

Values for counts 'Incomplete_Rides':
Incomplete_Rides
No     60041
Yes     3926
Name: count, dtype: int64

Values for counts 'Incomplete_Rides_Reason':
Incomplete_Rides_Reason
Customer Demand      1601
Vehicle Breakdown    1591
Other Issue           734
Name: count, dtype: int64

Values for counts 'Payment_Method':
Payment_Method
Cash           35022
UPI            25881
Credit Card     2435
Debit Card       629
Name: count, dtype: int64

In [10]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [11]:
df['Canceled_Rides_by_Customer'] = df['Canceled_Rides_by_Customer'].fillna('NA')
df['Canceled_Rides_by_Customer'].isnull().sum()
print(df.isnull().sum())

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [12]:
df['Canceled_Rides_by_Driver'] = df['Canceled_Rides_by_Driver'].fillna('NA')
df['Canceled_Rides_by_Driver'].isnull().sum()
print(df.isnull().sum())

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [13]:
df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna('NA')
df['Incomplete_Rides'].isnull().sum()
print(df.isnull().sum())

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [14]:
df['Incomplete_Rides_Reason'] = df['Incomplete_Rides_Reason'].fillna('NA')
df['Incomplete_Rides_Reason'].isnull().sum()
print(df.isnull().sum())

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [15]:
df['Payment_Method'] = df['Payment_Method'].fillna('NA')
df['Payment_Method'].isnull().sum()
print(df.isnull().sum())

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                     0
Payment_Method                    0
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [20]:
df_filled = df.fillna(df.mean(numeric_only=True))
print("\nMissing Values After")
print(df_filled.isnull().sum())
df_filled.to_csv('Cleaned_Bookings.csv', index=False)

Missing Values After
Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
dtype: int64