In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

df = pd.read_csv('my_file.csv')
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [ ]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [ ]:
df.describe().T

       count    mean        std   min    25%   50%     75%    max
Rank    20.0   10.45   5.942488   1.0   5.75  10.5   15.25   20.0
Shows   20.0  110.00  66.507617  41.0  59.00  87.0  134.50  325.0

In [ ]:
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("Categorical Columns:", cat_cols)
print("Numerical Columns:", num_cols)

for col in cat_cols:
  print("\nValues for counts '{col}':")
  print(df[col].value_counts())

Categorical Columns: ['Peak', 'All Time Peak', 'Actual\xa0gross', 'Adjusted\xa0gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)', 'Average gross', 'Ref.']
Numerical Columns: ['Rank', 'Shows']

Values for counts '{col}':
Peak
1        2
2[4]     2
1[4]     1
2[7]     1
2[10]    1
1[20]    1
2[c]     1
Name: count, dtype: int64

Values for counts '{col}':
All Time Peak
2         1
7[2]      1
2[5]      1
10[7]     1
10[9]     1
14[17]    1
Name: count, dtype: int64

Values for counts '{col}':
Actual gross
$780,000,000       1
$579,800,000       1
$411,000,000       1
$397,300,000       1
$345,675,146       1
$305,158,363       1
$280,000,000       1
$257,600,000       1
$256,084,556       1
$250,400,000       1
$229,100,000[b]    1
$227,400,000       1
$204,000,000       1
$200,000,000       1
$194,000,000       1
$184,000,000       1
$170,000,000       1
$169,800,000       1
$167,700,000[e]    1
$150,000,000       1
Name: count, dtype: int64

Values for counts '{col}':
Adjusted gross (in 2022 dollars)
$780,000,000    1
$579,800,000    1
$560,622,615    1
$454,751,555    1
$402,844,849    1
$388,978,496    1
$381,932,682    1
$257,600,000    1
$312,258,401    1
$309,141,878    1
$283,202,896    1
$295,301,479    1
$251,856,802    1
$299,676,265    1
$281,617,035    1
$227,452,347    1
$213,568,571    1
$207,046,755    1
$204,486,106    1
$185,423,109    1
Name: count, dtype: int64

Values for counts '{col}':
Artist
Taylor Swift    4
Madonna         4
Beyoncé         3
Pink            3
Lady Gaga       2
Celine Dion     1
Katy Perry      1
Cher            1
Adele           1
Name: count, dtype: int64

Values for counts '{col}':
Tour title
The Eras Tour †                             1
Renaissance World Tour                      1
Sticky & Sweet Tour ‡[4][a]                 1
Beautiful Trauma World Tour                 1
Reputation Stadium Tour                     1
The MDNA Tour                               1
Taking Chances World Tour                   1
Summer Carnival †                           1
The Formation World Tour                    1
The 1989 World Tour                         1
The Mrs. Carter Show World Tour             1
The Monster Ball Tour *                     1
Prismatic World Tour                        1
Living Proof: The Farewell Tour ‡[21][a]    1
Confessions Tour                            1
The Truth About Love Tour                   1
Born This Way Ball                          1
Rebel Heart Tour                            1
Adele Live 2016                             1
The Red Tour                                1
Name: count, dtype: int64

Values for counts '{col}':
Year(s)
2013–2014    3
2023–2024    2
2008–2009    2
2023         1
2018         1
2012         1
2016         1
2018–2019    1
2015         1
2009–2011    1
2014–2015    1
2002–2005    1
2006         1
2012–2013    1
2015–2016    1
2016–2017    1
Name: count, dtype: int64

Values for counts '{col}':
Average gross
$13,928,571    1
$10,353,571    1
$4,835,294     1
$2,546,795     1
$6,522,173     1
$3,467,709     1
$2,137,405     1
$6,282,927     1
$5,226,215     1
$2,945,882     1
$1,735,606     1
$1,118,227     1
$1,350,993     1
$615,385       1
$3,233,333     1
$1,295,775     1
$1,734,694     1
$2,070,732     1
$1,385,950     1
$1,744,186     1
Name: count, dtype: int64

Values for counts '{col}':
Ref.
[1]         1
[3]         1
[6]         1
[7]         1
[8]         1
[9]         1
[11]        1
[12]        1
[13]        1
[14]        1
[15][16]    1
[18]        1
[19]        1
[20]        1
[5]         1
[22]        1
[d]         1
[4]         1
[25]        1
[26]        1
Name: count, dtype: int64

In [ ]:
df.columns = (
    df.columns
      .str.strip()                       # remove leading/trailing spaces
      .str.lower()                       # optional: lowercase
      .str.replace(r"[()\^]", "", regex=True)  # remove (), ^
      .str.replace(r"\s+", "_", regex=True)    # replace spaces with underscore
)

In [ ]:
df.isnull().sum()

rank                               0
peak                              11
all_time_peak                     14
actual_gross                       0
adjusted_gross_in_2022_dollars     0
artist                             0
tour_title                         0
years                              0
shows                              0
average_gross                      0
ref.                               0
dtype: int64

In [ ]:
df['peak'] = df['peak'].fillna('NA')
df['peak'].isnull().sum()
print(df.isnull().sum())

rank                               0
peak                               0
all_time_peak                     14
actual_gross                       0
adjusted_gross_in_2022_dollars     0
artist                             0
tour_title                         0
years                              0
shows                              0
average_gross                      0
ref.                               0
dtype: int64

In [ ]:
df['all_time_peak'] = df['all_time_peak'].fillna('NA')
df['all_time_peak'].isnull().sum()
print(df.isnull().sum())

rank                              0
peak                              0
all_time_peak                     0
actual_gross                      0
adjusted_gross_in_2022_dollars    0
artist                            0
tour_title                        0
years                             0
shows                             0
average_gross                     0
ref.                              0
dtype: int64

In [ ]:
df.to_csv('cleaned_my_file.csv', index=False)